name: DeployToPages
env:
  PUBLISH_DIR: bin/Release/net6.0/publish

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish app
      working-directory: src
      run: dotnet publish -c Release